### ISSUE TITLE
Translated text overflows

### ISSUE THREAD

**Issue by viren-vii** [aasthasinha-19/Shakesperean-translator#1]
![image](https://user-images.githubusercontent.com/56278281/115387860-d906e080-a1f8-11eb-9337-71394116dee0.png)
Fixing CSS might fix the issue.
It is advisable to add static files to separate folder and have neat project structure for better understandability.

**Comment by aasthasinha-19** [comment]
Thank you for the suggestion.
I have tried to fix this in : d51fcb75e250d1a458dc0d9a9e370dbd35b7e9f5
